apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: landing-page-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: landing-page-tls
  issuerRef:
    name: {{ .Values.gateway.issuerRef.name | quote }}
    kind: {{ .Values.gateway.issuerRef.kind | quote }}
  dnsNames:
    - {{ .Values.gateway.hostname | quote }}
