apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  namespace: {{ .Release.Namespace }}
  labels:
    app: landing-page
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: landing-page
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      containers:
        - name: landing-page
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
            failureThreshold: 3
