apiVersion: v1
kind: Service
metadata:
  name: landing-page
  namespace: {{ .Release.Namespace }}
  labels:
    app: landing-page
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | quote }}
      protocol: TCP
